### ISSUE TITLE
Please add setup guideline for core

### ISSUE THREAD

**Issue by JoooJooo** [devvsda/shepherd#13]
Also, As part of single WF register and its execution. Do you have sample request and call precedure?

**Comment by JoooJooo** [comment]
https://github.com/devvsda/shepherd/tree/master/shephard-core/src/test/resources

**Comment by JoooJooo** [comment]
Here is the sample DAG and endpoint.

**Comment by devvsda** [comment]
Thanks for raising ticket. I am working on this.

**Comment by devvsda** [comment]
Fixed all the build issues.
Steps to setup Shepherd-Core doc is ready : https://github.com/devvsda/shepherd/blob/master/README.md

Closing this ticket.
